let myBody = document.body;
let myDiv1 = document.createElement("div");
let myDiv2 = document.createElement("div");
let myDiv3 = document.createElement("div");
let myDiv4 = document.createElement("div");
let div1Span = document.createElement("span");
let div1h1 = document.createElement("h1");
let div2P = document.createElement("p");
let div3date = new Date();
let div4p1 = document.createElement("p");
let div4p2 = document.createElement("p");
let div4p3 = document.createElement("p");
let div4p4 = document.createElement("p");
let div4p5 = document.createElement("p");
let div4p6 = document.createElement("p");
let div4p7 = document.createElement("p");

myDiv1.classList.add("myDiv1");
div1h1.classList.add("div1h1");
div2P.classList.add("div2P");
myDiv3.classList.add("myDiv3");
div4p1.classList.add("div4p1");
div4p2.classList.add("div4p2");
div4p3.classList.add("div4p3");
div4p4.classList.add("div4p4");
div4p5.classList.add("div4p5");
div4p6.classList.add("div4p6");
div4p7.classList.add("div4p7");
div1Span.textContent = "PLURARL CODE FULL STACK TRAINING PROGRAMME";
div1h1.textContent = 2024;
div2P.textContent = "30days of JavaScript Training";
div4p1.textContent = "30days of Python Training done";
div4p2.textContent = "30days of Javascript Training ongoing";
div4p3.textContent = "30days of React Training coming soon";
div4p4.textContent = "30days of React Native Training coming soon";
div4p5.textContent = "30days of HTML Training coming soon";
div4p6.textContent = "30days of Bootstrap Training coming soon";
div4p7.textContent = "30days of Tailwind CSS Training coming soon";
myBody.append(myDiv1);
myBody.append(myDiv2);
myBody.append(myDiv3);
myBody.append(myDiv4);
myDiv1.append(div1Span);
myDiv1.append(div1h1);
myDiv2.append(div2P);
myDiv3.append(div3date);
myDiv4.append(div4p1);
myDiv4.append(div4p2);
myDiv4.append(div4p3);
myDiv4.append(div4p4);
myDiv4.append(div4p5);
myDiv4.append(div4p6);
myDiv4.append(div4p7);
